name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Test & Build
        run: |
          python -m pip install --upgrade pip setuptools
          python pack.py
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: langful
          path: dist
      - name: Publish
        if: startsWith( github.ref , 'refs/tags' )
        uses: pypa/gh-action-pypi-publish@release/v1
